apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tarsbikecraft-deployment

spec:
  replicas: 2
  selector: 
    matchLabels:
      app: tarsbikecraft
  template:
      metadata: 
        labels:
          app: tarsbikecraft
      spec:
        containers:
          - name: tarsbike 
            image: jpablolima/apache2tarsbikecraft:latest
            resources:
              limits:
                memory: 512Mi
                cpu: "1"
             

   
