apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-tarsbike-craft
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tarsbike-craft
  template:
    metadata:
      labels:
        app: tarsbike-craft
    spec:
      containers:
      - name: webserver
        image: jpablolima/apache2tarsbikecraft:1.2.0
      
        
