name: Create Pull Request
on:
  push:
    branches:
      - feature 
  pull_request:
    branches:
      - main
jobs:
  CreatePullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Authors
        run: |
          git log --format='%aN <%aE>%n%cN <%cE>' | sort -u > AUTHORS
      
      - name: CreatePull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4

      
        with:
          token: ${{ secrets.GIT_TOKEN  }}
          commit-message: Create Pull Request
          title: Update Tars Bike Craft
          body:  Update Tars Bike Craft
          branch: main
          author: ${{ github.actor }} 
        
      - name: Checkout Outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
