name: Create Pull Request

on:
  push:
    branches:
      - develop 

jobs:
  CreatePullRequest:
    strategy:
      fail-fast: false
      matrix:
            runner: [ ubuntu-latest ]
    runs-on: ${{  matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: "develop"
          base: feature
          title: Auto Pull Request
          committer: ${{  env.GIT_COMMIT_AUTHOR_NAME  }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body: 
              Automatic Pull Request
          token: ${{ secrets.GIT_TOKEN }}
          # delete-branch: false
