name: Create Pull Request

on:
  push:
    branches:
      - develop 
  pull_request:
    branches:
      - develop

jobs:
  CreatePullRequest:
    strategy:
      fail-fast: true
      matrix:
            runner: [ ubuntu-latest ]
    runs-on: ${{  matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1
      
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GIT_TOKEN  }}
          commit-message: Create Pull Request
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: Update Tars Bike Craft
          body:  Update Tars Bike Craft
          branch: main
   
  