name: Create Pull Request

on:
  push:
    branches:
      - develop 

jobs:
  CreatePullRequest:
    strategy:
      fail-fast: false
      matrix:
            runner: [ ubuntu-latest ]
    runs-on: ${{  matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      
      # - name: Expose git commit data
      #   uses: rlespinasse/git-commit-data-action@v1
      
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GIT_TOKEN  }}
          commit-message: Create Pull Request
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: Update Tars Bike Craft
          body:  Update Tars Bike Craft
          branch: feature
      
      - name: Check Outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}" 
          echo "Pull Request Operation - ${{ steps.cpr.outputs.pull-request-operation }}" 
          echo "Pull Request SHA - ${{ steps.cpr.outputs.pull-request-head-sha }}" 
   
                 
      - name: Create or Update Project Card
        if: ${{ steps.cpr.outputs.pull-request-number }}
        uses: peter-evans/create-or-update-project-card@v2
        with:
           project-name: TarsBikeCraft
           column-name:  TarsBikeCraft
           issue-number: ${{ steps.cpr.outputs.pull-request-number }}
        



