name: Create Pull Request

on:
  push:
    branches:
      - "develop"

jobs:
  CreatePullReques:
    strategy:
      fail-fast: true
      matrix: 
        runner: [ ubuntu-latest ]
    runs-on: ${{  matrix.runner }}

    steps:
      - name: Checkout repo
        id: open-pr
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          pr_title: "Merge branch 'develop' into feature"
          destination_branch: feature
          pr_body: |
            :crown: *Update and automated PR*
          github_token: ${{  secrets.GIT_TOKEN  }}

      - name: Outputs
        run: echo ${{steps.open-pr.outputs.pr_url}}
      - name: output-created
        run: echo ${{steps.open-pr.outputs.pr_created}}
