name: Create Pull Request

on:
  push:
    branches:
      - feature 
  pull_request:
    branches:
      - main
jobs:
  CreatePullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: CreatePull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GIT_TOKEN  }}
          commit-message: Create Pull Request
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: Update Tars Bike Craft
          body:  Update Tars Bike Craft
          branch: main
      
      - name: Check Outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}" 
      
      
           
        

