name: Create Pull Request

on:
  push:
    branches:
      - feature 
  pull_request:
    branches:
      - main

jobs:
  CreatePullRequest:
    strategy:
      fail-fast: true
      matrix:
            runner: [ ubuntu-latest ]
    runs-on: ${{  matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1
      
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GIT_TOKEN  }}
          commit-message: Create Pull Request
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: Update Tars Bike Craft
          body:  Update Tars Bike Craft
          branch: main
      
      - name: Check Outputs
        # if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}" 
          echo "Pull Request Operation - ${{ steps.cpr.outputs.pull-request-operation }}" 
          echo "Pull Request SHA - ${{ steps.cpr.outputs.pull-request-head-sha }}" 
   
  DeployDockerImage:
    needs: CreatePullRequest
    strategy:
      fail-fast: true
      matrix:
             runner: [  ubuntu-latest ]
    runs-on: ${{  matrix.runner }}
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Login Docker Hub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN   }}
        
      - name: Build and Push
        uses: docker/build-push-action@v4
        id: result
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME  }}/apache2tarsbikecraft:latest
        
      - name: Outputs
        run: echo "${{ steps.result.outputs.result }}:latest"

          
      

                 

        



