name: Deploy Docker Image

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  DeployDockerImage:
    # needs: CreatePullRequest
    strategy:
      fail-fast: true
      matrix:
             runner: [  ubuntu-latest ]
    runs-on: ${{  matrix.runner }}
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Login Docker Hub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN   }}
        
      - name: Build and Push
        uses: docker/build-push-action@v4
        id: result
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME  }}/apache2tarsbikecraft:1.1.0
        
      # - name: Outputs
      #   run: echo "${{ steps.result.outputs.result }}:latest"

          
      

                 

        



