name: Create Pull Request

on:
  push:
    branches:
      - develop 

jobs:
  CreatePullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Auto Pull Request
          branch: develop
          base: feature
          committer: ${{  env.GIT_COMMIT_AUTHOR_NAME  }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body: 
              Automatic Pull Request
          token: ${{ secrets.GIT_TOKEN }}

